### ISSUE TITLE
I want to remove a key from the cache.

### ISSUE THREAD

**Issue by Yuhi-Sato** [catatsuy/cache#13]
I want to remove a key from the cache when executing SQL DELETE or UPDATE statements.

For example, how about the following implementation?

```go
func (c *ReadHeavyCache[K, V]) Delete(key K) {
	c.RLock()
        delete(c.items, key)
	c.RUnlock()
}
```

Thank you.

**Comment by catatsuy** [comment]
Thank you for the suggestion! @Yuhi-Sato 

I’ve implemented the feature as you described.
